// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options .dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcxHBCWobyOwUKDsqI_eZSlFDmOJ1WaaA',
    appId: '1:748212548066:web:c3d3dbe6806c00551cc9bb',
    messagingSenderId: '748212548066',
    projectId: 'phoenixmecano-dev',
    authDomain: 'phoenixmecano-dev.firebaseapp.com',
    storageBucket: 'phoenixmecano-dev.appspot.com',
    measurementId: 'G-HJRRWV0Q1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDyOcT4qnctAgwhSNiIz7YzUYskKC3xPM',
    appId: '1:748212548066:android:e9c2a934be83174c1cc9bb',
    messagingSenderId: '748212548066',
    projectId: 'phoenixmecano-dev',
    storageBucket: 'phoenixmecano-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7DFTjwjs4J7NNunQYrBRGJyvlTWLs_84',
    appId: '1:748212548066:ios:014943e64e2df3f51cc9bb',
    messagingSenderId: '748212548066',
    projectId: 'phoenixmecano-dev',
    storageBucket: 'phoenixmecano-dev.appspot.com',
    iosClientId:
        '748212548066-sbiama5401olofie2dem9ua820te84qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.pheonixMechanoNative',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7DFTjwjs4J7NNunQYrBRGJyvlTWLs_84',
    appId: '1:748212548066:ios:75ef9b661151902b1cc9bb',
    messagingSenderId: '748212548066',
    projectId: 'phoenixmecano-dev',
    storageBucket: 'phoenixmecano-dev.appspot.com',
    iosClientId:
        '748212548066-hrrca67c8s5ch55jaircngpdnl7ri2f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pheonixMechanoNative.RunnerTests',
  );
}
